# Generated by Django 2.2.2 on 2019-08-04 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('staion_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('total_seat', models.IntegerField(null=True)),
                ('time', models.TimeField(null=True)),
                ('station_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Station')),
            ],
        ),
        migrations.CreateModel(
            name='TicketPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(null=True)),
                ('destStation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dst', to='main.Station')),
                ('sourceStation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='main.Station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Train')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('destStation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingdst', to='main.Station')),
                ('passenger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Passenger')),
                ('sourceStation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingsrc', to='main.Station')),
                ('train', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Train')),
            ],
        ),
    ]
