# Generated by Django 2.2.2 on 2019-08-04 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='station_name',
        ),
        migrations.RemoveField(
            model_name='train',
            name='time',
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(null=True)),
                ('station_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Station')),
                ('train_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Train')),
            ],
        ),
    ]
